### ISSUE TITLE
New Minecket 4.0

### ISSUE THREAD

**Issue by henrythierrydev** [Henry8K/Minecket#2]
> Dear Minecket fans,

> we are excited to announce that we will soon be adding a powerful database system to our website, which will enhance your browsing and shopping experience. Additionally, we will be cleaning up our existing codes and improving our shopping cart and checkout systems to make the entire process smoother and more efficient for you.

> **The registration system will be discontinued and replaced with Login with nickname only!**

> By Henry8K and team.

**TODO**

- [x] JavaScript clean up.
- [x] Better CSS
- [x] Images scale fix
- [x] Responsive Fixies
- [x] New login system
- [x] New 505 and 404 pages
- [x] New responsive methods

**Comment by henrythierrydevalt** [comment]
Perhaps a css reorganization?

**Comment by henrythierrydev** [comment]
> Perhaps a css reorganization?

Sure.

**Comment by henrythierrydevalt** [comment]
For 404 pages, I have an idea to create an animation. What do you think? Do you like it?

**Comment by henrythierrydev** [comment]
I like the idea, but what kind of animation are you thinking of?

**Comment by PetterLight** [comment]
I'm still not sure. Are you thinking of something like a confused Steve animation?

**Comment by henrythierrydevalt** [comment]
I'm still not sure. what about a confused Steve animation?

**Comment by henrythierrydev** [comment]
Cool, do it

**Comment by henrythierrydevalt** [comment]
Css in the same page of html?

**Comment by henrythierrydev** [comment]
Idk, maybe yes...

**Comment by henrythierrydev** [comment]
Done.
